local player = game.Players.LocalPlayer
local TweenService = game:GetService("TweenService")

-- Tạo ScreenGui
local screenGui = Instance.new("ScreenGui", player:WaitForChild("PlayerGui"))
screenGui.ResetOnSpawn = false

-- Tạo Intro Label
local introLabel = Instance.new("TextLabel")
introLabel.Parent = screenGui
introLabel.Size = UDim2.new(1, 0, 1, 0)
introLabel.BackgroundTransparency = 1
introLabel.Text = "欢迎使用小西脚本"
introLabel.TextColor3 = Color3.new(2, 2, 1)
introLabel.TextScaled = true
introLabel.Font = Enum.Font.SourceSansBold

-- Tạo fade out Tween cho intro
task.delay(5, function()
	local fadeTween = TweenService:Create(introLabel, TweenInfo.new(1), {
		TextTransparency = 1
	})
	fadeTween:Play()
	fadeTween.Completed:Wait()
	introLabel:Destroy()
end)

-- Tạo nút chính, đợi 6s để intro biến mất
task.delay(6, function()
	local button = Instance.new("TextButton")
	button.Parent = screenGui
	button.Size = UDim2.new(0, 50, 0, 50)
	button.Position = UDim2.new(0.5, -100, 0.8, 0)
	button.Text = "小西脚本"
	button.BackgroundColor3 = Color3.fromRGB(80, 80, 255)
	button.TextColor3 = Color3.new(1, 1, 1)
	button.TextScaled = true
	button.Active = true
	button.Draggable = true

	-- Biến phát hiện kéo
	local dragging = false
	local dragStartPos = nil
	local dragThreshold = 10
	local pressTime = 0

	button.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.Touch or input.UserInputType == Enum.UserInputType.MouseButton1 then
			dragStartPos = input.Position
			dragging = false
			pressTime = tick()
		end
	end)

	button.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.Touch or input.UserInputType == Enum.UserInputType.MouseMovement then
			if dragStartPos and (input.Position - dragStartPos).Magnitude > dragThreshold then
				dragging = true
			end
		end
	end)

	button.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.Touch or input.UserInputType == Enum.UserInputType.MouseButton1 then
			local holdDuration = tick() - pressTime

			if not dragging and holdDuration < 1 then
				-- === KÍCH HOẠT CHIÊU ===

				-- Flowing Water
				local args1 = {
					[1] = {
						["Tool"] = player.Backpack:FindFirstChild("Flowing Water"),
						["Goal"] = "Console Move"
					}
				}
				player.Character.Communicate:FireServer(unpack(args1))

				task.wait(2.15)

				local char = player.Character
				if not char or not char:FindFirstChild("HumanoidRootPart") then return end
				local hrp = char.HumanoidRootPart

				local forward = hrp.CFrame.LookVector.Unit
				local distance = 20
				local duration = 0.1
				local goalPos = hrp.Position + forward * distance
				local tween = TweenService:Create(hrp, TweenInfo.new(duration), {
					CFrame = CFrame.new(goalPos, goalPos + forward)
				})
				tween:Play()
				tween.Completed:Wait()

				hrp.CFrame = hrp.CFrame * CFrame.Angles(0, math.rad(180), 0)

				-- Lethal Whirlwind Stream
-- Script generated by SimpleSpy - credits to exx#9394
local args = {
    [1] = {
        ["Tool"] = game:GetService("Players").LocalPlayer.Backpack:FindFirstChild("Lethal Whirlwind Stream"),
        ["Goal"] = "Console Move"
    }
}

game:GetService("Players").LocalPlayer.Character.Communicate:FireServer(unpack(args))
			end

			dragStartPos = nil
			dragging = false
		end
	end)
end)